server:
  port: 8082

spring:
  profiles:
    active: test
  application:
    name: diy-cosmetics-database
  security:
    user:
      password: ${ADMIN_PASS}
      name: admin
  datasource:
    url: jdbc:mysql://biologicznieczynny-diy/biologicznieczynny-diy?allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


