server:
  port: 8082

spring:
  application:
    name: diy-cosmetics-database
  security:
    user:
      password: test123
      name: jagodzinka
  datasource:
    url: jdbc:mysql://localhost:3306/biologicznieczynny-local?autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: demopass1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true

